/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votantes.componente;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javafx.scene.control.Spinner;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 1056374147
 */
//no se puede poner otros colores a las barras porque no existe un método setColores.
public class Ventana extends javax.swing.JFrame {

    //contadores
    int contadorBlanco = 0;
    int contadorRosa = 0;
    int contadorAzul = 0;
    int contadorVerde = 0;
//leyendas
    String tLeyenda[] = {" Blanco", " Rosa", " Azul", " Verde"};
//array de los datos 
    static ArrayList<Votantes> Votantes = new ArrayList<Votantes>();
    Votantes v1 = new Votantes("16161260", "8", false);
    Votantes v2 = new Votantes("16161261", "5", false);
    Votantes v3 = new Votantes("16161262", "5", false);
//array de los que ya votaron
    ArrayList<Votantes> yavoto = new ArrayList<Votantes>();
//colores de las barras
//    private static final Color color[] = {Color.WHITE, Color.PINK, Color.BLUE, Color.GREEN,};
    //no se puede poner otros colores a las barras porque no existe un método setColores.

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        grafico1.setLeyendas(tLeyenda);
        grafico1.setTitulo("Número de Votos x Planillas");

        this.estadosBtn(false);
        //agregando votantes
        Votantes.add(v1);
        Votantes.add(v2);
        Votantes.add(v3);
//imprime votantes en consola
        for (int i = 0; i < Votantes.size(); i++) {
            System.out.println("" + Votantes.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumControl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnValidar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBlanco = new javax.swing.JButton();
        btnRosa = new javax.swing.JButton();
        btnAzul = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        grafico1 = new com_grafico.Grafico();
        jLabel8 = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese: Núm. Control:");

        jLabel2.setText("Semestre:");

        btnValidar.setText("Valida Votante");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Da un click en la planilla de la elección para votar:");

        btnBlanco.setBackground(new java.awt.Color(255, 255, 255));
        btnBlanco.setText("BLANCO");
        btnBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlancoActionPerformed(evt);
            }
        });

        btnRosa.setBackground(new java.awt.Color(255, 153, 255));
        btnRosa.setText("ROSA");
        btnRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRosaActionPerformed(evt);
            }
        });

        btnAzul.setBackground(new java.awt.Color(51, 102, 255));
        btnAzul.setText("AZUL");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        btnVerde.setBackground(new java.awt.Color(153, 255, 0));
        btnVerde.setText("VERDE");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRosa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnResultado.setText("Terminar Proceso de Votaciones");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        jLabel8.setText("Votaciones por planillas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(btnValidar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grafico1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnValidar)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnResultado)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addComponent(grafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        buscarvotante(txtNumControl.getText(), txtSemestre.getValue().toString(), false);
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        int[] valores = {contadorBlanco, contadorRosa, contadorAzul, contadorVerde};
        grafico1.setVals(valores);
        grafico1.repaint();
        this.planillaganadora();
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btnBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlancoActionPerformed
        contadorBlanco += 1;
        guardarVoto(buscarvotante(txtNumControl.getText(), txtSemestre.getValue().toString(), false));
    }//GEN-LAST:event_btnBlancoActionPerformed

    private void btnRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRosaActionPerformed
        contadorRosa += 1;
        guardarVoto(buscarvotante(txtNumControl.getText(), txtSemestre.getValue().toString(), false));
    }//GEN-LAST:event_btnRosaActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        contadorAzul += 1;
        guardarVoto(buscarvotante(txtNumControl.getText(), txtSemestre.getValue().toString(), false));
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        contadorVerde += 1;
        guardarVoto(buscarvotante(txtNumControl.getText(), txtSemestre.getValue().toString(), false));
    }//GEN-LAST:event_btnVerdeActionPerformed

    private Votantes buscarvotante(String Ncontrol, String Sem, boolean vote) {
        Votantes votante = new Votantes(Ncontrol, Sem, vote);
        if (txtNumControl.getText().equalsIgnoreCase("") || txtSemestre.getValue().toString().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Elementos vacios");
            return null;
        } else if (votante.getNumcontrol().equals(v1.getNumcontrol()) && votante.getSemestre().equals(v1.getSemestre())) {
            yavotaste(v1);
            return v1;
        } else if (votante.getNumcontrol().equals(v2.getNumcontrol()) && votante.getSemestre().equals(v2.getSemestre())) {
            yavotaste(v2);
            return v2;
        } else if (votante.getNumcontrol().equals(v3.getNumcontrol())&& votante.getSemestre().equals(v3.getSemestre())) {
            yavotaste(v3);
            return v3;
        } else {
            JOptionPane.showMessageDialog(this, "No existe en el padrón");
            this.estadosBtn(false);
            return null;
        }
    }

    private Votantes guardarVoto(Votantes votante) {
        if (votante.getNumcontrol().equals(v1.getNumcontrol())) {
            v1.setVoto(true);
            yavoto.add(v1);
            this.estadosBtn(false);
            return v1;
        } else if (votante.getNumcontrol().equals(v2.getNumcontrol())) {
            v2.setVoto(true);
            yavoto.add(v2);
            this.estadosBtn(false);
            return v2;
        } else if (votante.getNumcontrol().equals(v3.getNumcontrol())) {
            v3.setVoto(true);
            yavoto.add(v3);
            this.estadosBtn(false);
            return v3;
        }
        return null;
    }

    private void estadosBtn(boolean estado) {
        btnBlanco.setEnabled(estado);
        btnRosa.setEnabled(estado);
        btnAzul.setEnabled(estado);
        btnVerde.setEnabled(estado);
    }

    private boolean yavotaste(Votantes v) {
        if (yavoto.contains(v)) {
            JOptionPane.showMessageDialog(this, "Ya hiciste tu voto");
            this.estadosBtn(false);
            return true;
        } else {
            this.estadosBtn(true);
            return false;
        }
    }

    private void planillaganadora() {
        int A = contadorBlanco;
        int B = contadorRosa;
        int C = contadorAzul;
        int D = contadorVerde;
        int X = 0;

        System.out.println("\n////YA VOTARON");
        for (int i = 0; i < yavoto.size(); i++) {
            System.out.println("" + yavoto.get(i));
        }

        if (A > B && A > C && A > D) {
            X = A;
            JOptionPane.showMessageDialog(null, "La planilla ganadora es LA BLANCA con : " + X + " votos");
        } else {
            if (B > A && B > C && B > D) {
                X = B;
                JOptionPane.showMessageDialog(null, "La planilla ganadora es LA ROSA con : " + X + " votos");
            } else {
                if (C > A && C > B && C > D) {
                    X = C;
                    JOptionPane.showMessageDialog(null, "La planilla ganadora es LA AZUL con : " + X + " votos");
                } else {
                    X = D;
                    JOptionPane.showMessageDialog(null, "La planilla ganadora es LA VERDE con : " + X + " votos");
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzul;
    private javax.swing.JButton btnBlanco;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnRosa;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnVerde;
    private com_grafico.Grafico grafico1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumControl;
    private javax.swing.JSpinner txtSemestre;
    // End of variables declaration//GEN-END:variables
}
